recfin/urls.py
from django.contrib import admin
from django.urls import path
from app.views import desserts_without_equipment
from app.views import show_dish_details
from app.views import dish_list
from app.views import meat_dishes_with_oven
from accounts import views
from django.contrib.auth.views import LogoutView
from app.views import ingredient_list
from app.views import search_dishes, AddUserView, DeleteUserView
from app.views import ingredient_list_admin,ingredient_edit, bluds_list, bluds_list_admin, bluds_edit, delete, delete_order
from dishs.views import add_dish, manage_permissions, update_permissions, add_ingred, delete_ingred, edit_order,add_order
app_name = 'dishs' 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('desserts-without-equipment/', desserts_without_equipment, name='desserts_without_equipment'),
    path('show_dish_details/', show_dish_details, name='show_dish_details'),
    path('meat_dishes_with_oven/', meat_dishes_with_oven, name='meat_dishes_with_oven'),
    path('dish_list/',dish_list, name='dish_list'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('bluds/list', bluds_list, name='bluds_list'),
    path('bluds/list/admin', bluds_list_admin, name='bluds_list_admin'),
    path('bluds/<int:dish_id>/edit/', bluds_edit, name='bluds_edit'),
    path('dish/<int:dish_id>/delete/', delete, name='delete'),
    path('search_dishes/', search_dishes, name='search_dishes'),
    path('ingredient/list/', ingredient_list, name='ingredient_list'),
    path('ingredient/list/admin', ingredient_list_admin, name='ingredient_list_admin'),
    path('ingredient/<int:ingredient_id>/edit/', ingredient_edit, name='ingredient_edit'),
    path('add_dish/', add_dish, name='add_dish'),
    path('manage-permissions/', manage_permissions, name='manage_permissions'),
    path('update-permissions/', update_permissions, name='update_permissions'),
    path('add_ingred/', add_ingred, name='add_ingred'),
    path('ingredient/<int:ingredient_id>/delete_ingred/', delete_ingred, name='delete_ingred'),
    path('add_order/', add_order, name='add_order'),
    path('edit_order/<int:order_id>/', edit_order, name='edit_order'),
    path('orders/<int:order_id>/delete/', delete_order, name='delete_order'),
    path('user/add/', AddUserView.as_view(), name='add_user'),
    path('delete-user/<int:user_id>/', DeleteUserView.as_view(), name='delete_user')

]

app/models.py
from django.db import models
from django.utils import timezone
from django import forms

# Create your models here.
class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    unit = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    
class Order(models.Model):
    name = models.ForeignKey('Ingredient', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    recipe = models.ForeignKey('Dish', on_delete=models.CASCADE)
    order = models.BigIntegerField()

    def __str__(self):
        return str(self.name)
    
class Dish(models.Model):
    name = models.CharField(max_length=100)
    weight = models.DecimalField(max_digits=10, decimal_places=2)
    calory = models.FloatField()
    time = models.DecimalField(max_digits=10, decimal_places=2)
    timehours = models.TextField()
    price_dish = models.BigIntegerField()
    type = models.ForeignKey('Type', on_delete=models.CASCADE)
    season = models.ForeignKey('Season', on_delete=models.CASCADE)
    equip = models.ForeignKey('RecipeEquipment', on_delete=models.CASCADE)

    
    def __str__(self):
        return self.name
    
class RecipeEquipment(models.Model):
    name = models.CharField(max_length=100)
    price_eq = models.BigIntegerField()
    
    def __str__(self):
        return self.name
    
class Season(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
class Type(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Meta:
    verbose_name_plural= "Entries"

app/templates/ingredient_edit_admin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
  <link rel="shortcut icon" href="{% static 'css/icon.png' %}" type="image/png">
<head>
    <title>Редактирование ингредиента</title>
</head>
<style>
  form {
    font-size: 20px;
    font-family: 'Candara';
  }
  
  form input,
  form select,
  form textarea {
    font-size: 18px;
  }
  
  form p {
    font-size: 23px;
    font-family: 'Candara';
  }
  button {
    background-color: #436430;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    font-size: 18px;
    cursor: pointer;
    margin-top: 10px;
    margin-bottom: 10px;
  }
</style>
<body>
    <h1>Редактирование ингредиента</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Сохранить</button>
    </form>
</body>
</html>
{% endblock %}

app/templates/ingredient_list.html
{% extends 'base.html' %}

{% block title %}Ингредиенты{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/ingred.css' %}">
<style>
    /* Custom styles */
    .ingredient-title {
        font-size: 30px;
        font-weight: bold;
        font-family: 'Candara';
    }

    .ingredient-table {
        width: 100%;
        border-collapse: separate;
        border-spacing: 0 10px; /* Add spacing between rows (adjust the value as needed) */
        margin-bottom: 20px;
        font-family: 'Inter', sans-serif;
    }

    .ingredient-table th,
    .ingredient-table td {
        padding: 10px;
        text-align: center;
        border: 1px solid rgba(0, 0, 0, 0);
        border-radius: 10px;
        font-size: 19px;
    }

    .ingredient-table thead {
        background-color: #436430;
        color: #fff;
    }

    .ingredient-table th {
        font-weight: bold;
    }
    .ingredient-table tbody tr {
        background-color: #ffffff;
    }
    .ingredient-table tbody tr:hover {
        background-color: #436430;
        color: #fff;
    }
    .save-button {
        margin-top: 20px;
        text-align: center;
    }
    button {
        background-color: #436430;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 4px;
        font-size: 18px;
        cursor: pointer;
        margin-top: 10px;
        margin-bottom: 30px;
}
    .content {
        margin: 20px auto;
        max-width: 100%;
        text-align: center;
    }
    
</style>


<h3 class="ingredient-title">Список ингредиентов</h3>
<link rel="shortcut icon" href="{% static 'css/icon.png' %}" type="image/png">
<table class="ingredient-table">
    <thead>
        <tr>
            <th>Ингредиент</th>
            <th>Блюда, в которых используется</th>
        </tr>
    </thead>
    <tbody>
        {% for ingredient in ingredients %}
            <tr>
                <td> {{ ingredient.name }} </td>
                <td>
                    {% for order in ingredient.order_set.all %}
                        {{ order.recipe.name }} (порядок - {{ forloop.counter }}, {{ order.amount }} {{ order.name.unit }})
                        {% if not forloop.last %}, {% endif %}
                    {% empty %}
                        Нет блюд
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </tbody>       
</table>
<div class="save-button">
    <button onclick="exportToJson('dishes.json')">Сохранить в JSON</button>
</div>
<script>
    function exportToJson(filename) {
        var ingredients = Array.from(document.querySelectorAll('.ingredient-table tbody tr')).map(function(row) {
            var cols = row.querySelectorAll('td');
            return {
                ingredient: cols[0].innerText,
                dishes: cols[1].innerText
            };
        });

        var jsonData = JSON.stringify(ingredients);

        var element = document.createElement('a');
        element.setAttribute('href', 'data:text/json;charset=utf-8,' + encodeURIComponent(jsonData));
        element.setAttribute('download', filename);
        element.style.display = 'none';
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    }
</script>

{% endblock %}

app/templates/ingredient_list_admin.html
{% extends 'base.html' %}

{% block title %}Ингредиенты{% endblock %}

{% block content %}
{% load static %}
<link rel="shortcut icon" href="{% static 'css/icon.png' %}" type="image/png">
<link rel="stylesheet" href="{% static 'css/ingred.css' %}">
<style>
    /* Custom styles */
    .ingredient-title {
        font-size: 30px;
        font-weight: bold;
        font-family: 'Candara';
    }
    .smile{
        font-size: 16px;
        color: #000000;
        font-style:bold;
        font-family: 'Inter', sans-serif;   
    }
    .ingredient-table {
        width: 100%;
        border-collapse: separate;
        border-spacing: 0 10px; /* Add spacing between rows (adjust the value as needed) */
        margin-bottom: 20px;
        font-family: 'Candara';
        font-size: 20px;
        margin-top:20px;
    }

    .ingredient-table th,
    .ingredient-table td {
        padding: 10px;
        text-align: center;
        border: 1px solid rgba(0, 0, 0, 0);
        border-radius: 10px;
    }
    td {
        font-size: 18px;
        color: #000000;
        font-style:bold;
        font-family: 'Inter', sans-serif; 
    }
    .ingredient-table thead {
        background-color: #436430;
        color: #fff;
    }

    .ingredient-table th {
        font-weight: bold;
    }
    .ingredient-table tbody tr {
        background-color: #ffffff;
    }
    .ingredient-table tbody tr:hover {
        background-color: #436430;
        color: #fff;
    }
    .save-button {
        margin-top: 20px;
        text-align: center;
    }
    .add-dish-button {
        font-size: 20px;
        font-weight: bold;
        color: #436430;
        font-family: 'Candara';
}
    button {
        background-color: #436430;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 4px;
        font-size: 18px;
        cursor: pointer;
        margin-top: 10px;
        }
</style>


<h3 class="ingredient-title" style="margin-bottom: 10px;">Список ингредиентов</h3>
<form method="GET" style=" display: flex;
flex-direction: column;
flex-wrap: wrap;
align-content: center;
justify-content: center;">
    <div>
        <a href="{% url 'add_ingred' %}" class="add-dish-button">➕ Добавить ингредиент</a>
    </div>
</form>
<table class="ingredient-table">
    <thead>
        <tr>
            <th>Ингредиент</th>
            <th>Блюда, в которых используется</th>
        </tr>
    </thead>
    <tbody>
        {% for ingredient in ingredients %}
            <tr>
                <td> {{ ingredient.name }}<a class="smile" href="{% url 'ingredient_edit' ingredient_id=ingredient.id %}">📝</a><a class="smile" href="{% url 'delete_ingred' ingredient_id=ingredient.id %}">❌</a></td>
                <td>
                    {% for order in ingredient.order_set.all %}
                        {{ order.recipe.name }} (порядок - {{ order.order }}<a class="smile" href="{% url 'edit_order' order_id=order.id %}">📝</a>, {{ order.amount }} {{ order.name.unit }})
                        {% if not forloop.last %}, {% endif %}
                    {% empty %}
                        Нет блюд
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </tbody>       
</table>
<div class="save-button">
    <button onclick="exportToJson('dishes.json')">Сохранить в JSON</button>
</div>
<script>
    function exportToJson(filename) {
        var ingredients = Array.from(document.querySelectorAll('.ingredient-table tbody tr')).map(function(row) {
            var cols = row.querySelectorAll('td');
            return {
                ingredient: cols[0].innerText,
                dishes: cols[1].innerText
            };
        });

        var jsonData = JSON.stringify(ingredients);

        var element = document.createElement('a');
        element.setAttribute('href', 'data:text/json;charset=utf-8,' + encodeURIComponent(jsonData));
        element.setAttribute('download', filename);
        element.style.display = 'none';
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    }
</script>

{% endblock %}